import Head from 'next/head'
import { Text } from 'react-dom'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
                    <a>This site works on Netlify server</a>
        </h1>

            <p>
              Laba diena. Hello. Hej. 
            </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.facebook.com/mindaugas.masiulis.5"
          target="_blank"
          rel="noopener noreferrer"
        >
          Contact developer Mindaugas Masiulis on Facebook
        </a>
      </footer>
    </div>
  )
}
