import Head from 'next/head'
import { Box, Stack, Button, Text as TextR, Input, Checkbox } from '@chakra-ui/react';
import { Text } from 'react-dom'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useRef, useState} from "react";
import "../worker1.js";

// function workerM() {
//   var myWorker = new Worker(new URL('./worker.js', import.meta.url));
//   myWorker.addEventListener('message', function(e) {
//     console.log('Message from Worker: ' + e.data);
//   })
//   // @ts-ignore
//   myWorker.postMessage('Hello World');

// }
function useWorker() {
    const workerRef = React.useRef(null);
    const [data, setData] = React.useState([]);
  
    React.useEffect(() => {
      workerRef.current = new Worker(new URL('../worker1.js', import.meta.url));
      workerRef.current.onmessage = (event) => {
        setData(event.data);
        console.log(event.data);
      };
      return () => {
        workerRef.current.terminate();
      };
    }, []);
  
    const handlePostMessage = () => {
      const a = 'aha';
      workerRef.current.postMessage({
        a
      });
    };
  
    return { handlePostMessage, data };
}
  


export default function Home() {
  const { data, handlePostMessage } = useWorker();
  const handleClick = async () => {
    try {
      //setIsLoading(true);
      // @ts-ignore
      handlePostMessage();
    } catch (e) {
      //console.log(e);
      // setResult([]);
      // setIsLoading(false);
    }
  };
  return (
    <div className={styles.container}>
      <Stack>
        
        <Button onClick={ handleClick}>Press me to start calculating</Button>
        <TextR>{data}</TextR>
      </Stack>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
                    <a>This site works on Netlify server</a>
                    
        </h1>
            <p>
              Laba diena. Hello. Hej. 
            </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.facebook.com/mindaugas.masiulis.5"
          target="_blank"
          rel="noopener noreferrer"
        >
          Contact developer Mindaugas Masiulis on Facebook
        </a>
      </footer>
    </div>
  )
}
