import Head from 'next/head'
import { Box, Stack, Button, Text as TextR, Input, Checkbox, textDecoration, Spacer } from '@chakra-ui/react';
import { Text } from 'react-dom';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React, {useRef, useState} from "react";
import {wrap} from "comlink";
import {useWebworker} from '../utils/hooks/use-webworker';

export default function Home() {
const [value, setValue] =useState(null);
 const {result, run} = useWebworker((k) => k * k);

 const handleValueChange=()=>{
   setValue(event.target.value)
 }

 const handlerClick =()=>{
   run(value)
 }

  return (
    <div className={styles.container}>
      <Stack>
        <Spacer height="100px"></Spacer>
        <Input placeholder='value' onChange={handleValueChange}></Input>
        <Button onClick={handlerClick}>Press me to start calculating</Button>
        <TextR className='result'>{result}</TextR>
      </Stack>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
                    <a>This site works on Netlify server</a>
                    
        </h1>
            <p>
              Laba diena. Hello. Hej. 
            </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.facebook.com/mindaugas.masiulis.5"
          target="_blank"
          rel="noopener noreferrer"
        >
          Contact developer Mindaugas Masiulis on Facebook
        </a>
      </footer>
    </div>
  )
}
